name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ✅ Create the S3 bucket only if it doesn't exist
      - name: Create S3 bucket if not exists
        run: |
          BUCKET_NAME=aws-ci-cd-fe
          REGION=${{ secrets.AWS_REGION }}

          echo "Checking if bucket '$BUCKET_NAME' exists..."
          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "✅ Bucket already exists. Skipping creation."
          else
            echo "🪣 Bucket not found. Creating..."
            aws s3api create-bucket \
              --bucket "$BUCKET_NAME" \
              --region "$REGION" \
              --create-bucket-configuration LocationConstraint="$REGION"

            echo "Enabling static website hosting..."
            aws s3 website s3://$BUCKET_NAME --index-document index.html --error-document error.html

            echo "✅ Bucket created successfully!"
          fi

      # ✅ Upload or update files to S3 bucket
      - name: Sync files to S3
        run: |
          BUCKET_NAME=aws-ci-cd-fe
          echo "Syncing files to S3 bucket: $BUCKET_NAME"
          aws s3 sync . s3://$BUCKET_NAME --delete
          echo "✅ Files synced successfully!"

      - name: Print website URL
        run: |
          REGION=${{ secrets.AWS_REGION }}
          echo "🌐 Website URL:"
          echo "http://aws-ci-cd-fe.s3-website-$REGION.amazonaws.com"
